stages:
  - checks

default:
  image: virtuatable/mongo-ruby-ci:1.0.1
  cache:
    key: $(CI_COMMIT_REF_SLUG)
    paths:
      - vendor/ruby
  before_script:
    - /bin/bash --login
    # Installs the Bundler dependencies to later get gems
    - gem install bundler --no-document
    # Sets the path used for caching purposes, and install dependencies
    - /bundle config set path vendor/ruby && bundle install

rspec:
  stage: checks
  script: bundle exec rspec

rubocop:
  stage: checks
  script: bundle exec rubocop